/*
 * File: app/view/containerDescripProyecto.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerDescripProyecto', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer',

    config: {
        id: 'containerDescripProyecto',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Buses UCR'
            },
            {
                xtype: 'panel',
                height: '80%',
                html: '<font color="gray"><center><p style="font-size: 150%;">Información general</p></center><p>&nbsp</p><p style="font-size:100%;"><p align="justify">Este proyecto surge como una iniciativa de la Escuela de Ingeniería Eléctrica de la Universidad de Costa Rica para ofrecer al usuario del transporte interno de la Sede Rodrigo Facio un servicio de geolocalización de buses en tiempo real.</p><p>Los creadores son:</p><p>Prototipo: <b>André Govinda Stahl Leitón</b></p><p>Aplicación: <b>Gustavo Hidalgo Ramírez</b></p><p>Profesor Guía: <b>Ing. Fabián Abarca Calderón</b></p></p></font>',
                left: '10%',
                top: '10%',
                width: '80%',
                modal: true,
                scrollable: 'vertical'
            }
        ]
    }

});