/*
 * File: app/view/containerInfo.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerInfo', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer11',

    config: {
        id: 'containerInfo',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Información',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Ext.getCmp('listaDespliegueInfo').removeAll();

                            clearTimeout(variableTimeOutBuffer);
                            Ext.getCmp('listaDespliegueInfo').setStore(null);
                            Ext.getCmp('panelInfoDespuesClickear').setHtml('');
                        },
                        right: '3%',
                        width: '18%',
                        iconCls: 'delete'
                    }
                ]
            },
            {
                xtype: 'container',
                html: '<center><font color="#29088A"><p>&nbsp</p><p>Despliegue por</p></font></center>',
                width: '49%',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp('containerEleccionPines').setMasked({xtype: "loadmask", message: "Espere por favor..."});
                            try{
                                Ext.getCmp('listaDespliegueInfo').getStore().removeAll();
                            }
                            catch(e){}
                            Ext.getCmp('listaDespliegueInfo').setItemTpl('');
                            Ext.getCmp('listaDespliegueInfo').setStore(null);
                            Ext.getCmp('panelInfoDespuesClickear').setHtml('');

                            MyApp.app.ejectBotonesDespliegue('parada');
                        },
                        height: '10%',
                        left: '15%',
                        top: '60%',
                        width: '70%',
                        text: 'Paradas'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp('containerEleccionPines').setMasked({xtype: "loadmask", message: "Espere por favor..."});
                            try{
                                Ext.getCmp('listaDespliegueInfo').getStore().removeAll();
                            }
                            catch(e){}
                            Ext.getCmp('listaDespliegueInfo').setItemTpl('');
                            Ext.getCmp('listaDespliegueInfo').setStore(null);
                            Ext.getCmp('panelInfoDespuesClickear').setHtml('');

                            MyApp.app.ejectBotonesDespliegue('bus');
                        },
                        height: '10%',
                        left: '15%',
                        top: '75%',
                        width: '70%',
                        text: 'Buses'
                    },
                    {
                        xtype: 'panel',
                        height: '30%',
                        id: 'panelInfoDespuesClickear',
                        left: '5%',
                        top: '16%',
                        width: '90%'
                    }
                ]
            },
            {
                xtype: 'container',
                height: '100%',
                left: '49.8%',
                style: 'background-color: black',
                width: '0.4%'
            },
            {
                xtype: 'container',
                height: '100%',
                left: '50.2%',
                width: '49.8%',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'list',
                        id: 'listaDespliegueInfo',
                        loadingText: 'Cargando...'
                    }
                ]
            }
        ]
    }

});